version: "3.2"
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - "tap_obscore"
    volumes:
      - "./docker/proxy/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/proxy/html:/usr/share/nginx/html"
    depends_on:
      - "obscore"
  obscore:
    image: opencadc/alma-tap:1.1.7
    depends_on:
      - "tapdb"
    ports:
      - "5555:5555"
    networks:
      - "tap_obscore"
    env_file:
      - "./docker/config/alma-tap.properties"
  tapdb:
    image: opencadc/tap-oracle:11-xe
    shm_size: 1gb
    networks:
      - "tap_obscore"
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d/startup"

networks:
  tap_obscore:
