# This is NOT a job and will be ignored by GitLab-CI
.shared_hidden_key: &shared_deploy  # This is an anchor
  before_script:
    - apk --no-cache add git
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  script:
    - export VERSION=`git log -1 --pretty=%H`
    - docker build --no-cache --pull --network host -t ${CI_REGISTRY_ORGANIZATION}/alma-${name}:${VERSION} -f ${module}/Dockerfile ${module}/
    - docker push ${CI_REGISTRY_ORGANIZATION}/alma-${name}:${VERSION}
  stage: deploy
  image: docker:latest
  services:
    - docker:dind

build_data:
  stage: build
  image: gradle:jdk11
  artifacts:
    paths:
      - data/build
  script:
    # This will install cadc-data-ops-fits 0.2.3 to include WCS cutouts.
    - export CURR_DIR
    - apt-get update && apt-get install -y curl gcc git make
    - curl -Lv -o /tmp/wcslib.tar.bz2 https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/wcslib/5.15-1/wcslib_5.15.orig.tar.bz2
    - cd /tmp/ && tar jxvf wcslib.tar.bz2 && cd wcslib-5.15
    - ./configure --prefix=/usr
    - make && make install
    - cd ${CI_PROJECT_DIR}/data && ../gradlew -i clean build test

build_datalink:
  stage: build
  image: gradle:jdk11
  artifacts:
    paths:
      - datalink/build
  script:
    - cd alma-lib && ../gradlew -i clean build test publishToMavenLocal
    - cd ../datalink && ../gradlew -i clean build test

build_tap:
  stage: build
  image: gradle:jdk11
  artifacts:
    paths:
      - tap/build
  script:
    - cd tap && ../gradlew -i clean build test

build_reg:
  stage: build
  image: gradle:jdk11
  artifacts:
    paths:
      - reg/build
  script:
    - cd reg && ../gradlew -i clean build test

build_sia:
  stage: build
  image: gradle:jdk11
  artifacts:
    paths:
      - sia/build
  script:
    - cd sia && ../gradlew -i clean build test

build_soda:
  stage: build
  image: gradle:jdk11
  artifacts:
    paths:
      - soda/build
  script:
    - cd alma-lib && ../gradlew -i clean build test publishToMavenLocal
    - cd ../soda && ../gradlew -i clean build test

deploy_data:
  variables:
    name: data
    module: data
  needs:
    - build_data
  <<: *shared_deploy  # This is a reference to the anchor above.

deploy_datalink:
  variables:
    name: datalink
    module: datalink
  needs:
    - build_datalink
  <<: *shared_deploy  # This is a reference to the anchor above.

deploy_reg:
  variables:
    name: reg
    module: reg
  needs:
    - build_reg
  <<: *shared_deploy  # This is a reference to the anchor above.

deploy_sia:
  variables:
    name: sia
    module: sia
  needs:
    - build_sia
  <<: *shared_deploy  # This is a reference to the anchor above.

deploy_soda:
  variables:
    name: soda
    module: soda
  needs:
    - build_soda
  <<: *shared_deploy  # This is a reference to the anchor above.

deploy_tap:
  variables:
    name: tap
    module: tap
  needs:
    - build_tap
  <<: *shared_deploy  # This is a reference to the anchor above.
