image: gradle:jdk11

build_data:
  stage: build
  script:
    - cd data && ../gradlew -i clean build test

build_datalink:
  stage: build
  script:
    - cd alma-lib && ../gradlew -i clean build test publishToMavenLocal
    - cd ../datalink && ../gradlew -i clean build test

build_obscore:
  stage: build
  script:
    - cd obscore && ../gradlew -i clean build test

build_reg:
  stage: build
  script:
    - cd reg && ../gradlew -i clean build test

build_sia:
  stage: build
  script:
    - cd sia && ../gradlew -i clean build test

build_soda:
  stage: build
  script:
    - cd alma-lib && ../gradlew -i clean build test publishToMavenLocal
    - cd ../soda && ../gradlew -i clean build test
