stages:
  - build_lib
  - build
  - test
  - deploy

image: gradle:jdk11

build_install_alma-lib:
  stage: build_lib
  artifacts:
    paths:
      - /root/.m2
  script:
    - cd alma-lib && ../gradlew -i clean build test publishToMavenLocal

build_data:
  stage: build
  needs: [build_install_alma-lib]
  dependencies:
    - build_install_alma-lib
  script:
    - cd data && ../gradlew -i clean build test

build_datalink:
  stage: build
  needs: [build_install_alma-lib]
  dependencies:
    - build_install_alma-lib
  script:
    - cd datalink && ../gradlew -i clean build test

build_obscore:
  stage: build
  needs: [build_install_alma-lib]
  dependencies:
    - build_install_alma-lib
  script:
    - cd obscore && ../gradlew -i clean build test

build_reg:
  stage: build
  needs: [build_install_alma-lib]
  dependencies:
    - build_install_alma-lib
  script:
    - cd reg && ../gradlew -i clean build test

build_sia:
  stage: build
  needs: [build_install_alma-lib]
  dependencies:
    - build_install_alma-lib
  script:
    - cd sia && ../gradlew -i clean build test

build_soda:
  stage: build
  needs: [build_install_alma-lib]
  dependencies:
    - build_install_alma-lib
  script:
    - cd soda && ../gradlew -i clean build test
