language: java

dist: trusty
sudo: required

jdk:
  - openjdk8
  - openjdk11

before_install:
  - gradle --version

script: for mod in obscore sia reg; do cd $mod; gradle -i assemble check javadoc || break -1; cd ..; done
