version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    image: nginx:alpine
    ports:
      - '443:443'
    networks:
      - 'alma'
    volumes:
      - './docker/proxy/default-ssl.conf:/etc/nginx/conf.d/default.conf'
      - 'server_certs:/usr/share/nginx/certs'
    depends_on:
      - 'obscore.cadc.dao.nrc.ca'
      - 'sia.cadc.dao.nrc.ca'
      - 'reg.cadc.dao.nrc.ca'
  sia.cadc.dao.nrc.ca:
    image: opencadc/alma-sia:SNAPSHOT
    build: ./sia/
    networks:
      - 'alma'
    ports:
      - '15555:5555'
    depends_on:
      - 'obscore.cadc.dao.nrc.ca'
    environment:
      CATALINA_OPTS: '-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca'
  obscore.cadc.dao.nrc.ca:
    image: opencadc/alma-tap:SNAPSHOT
    build: ./obscore/
    ports:
      - '35555:5555'
    networks:
      - 'alma'
    env_file:
      - './obscore/docker/config/alma-tap.properties'
  reg.cadc.dao.nrc.ca:
    image: opencadc/alma-reg:SNAPSHOT
    build: ./reg/
    networks:
      - 'alma'
    ports:
      - '25555:5555'
    environment:
      CATALINA_OPTS: '-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca'

networks:
  alma:

volumes:
  server_certs:
    external: true