version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    image: nginx:alpine
    ports:
      - '443:443'
    networks:
      - 'alma'
    volumes:
      - './docker/proxy/default-ssl.conf:/etc/nginx/conf.d/default.conf'
      - 'server_certs:/usr/share/nginx/certs'
    depends_on:
      - 'obscore.cadc.dao.nrc.ca'
      - 'sia.cadc.dao.nrc.ca'
      - 'reg.cadc.dao.nrc.ca'
  sia.cadc.dao.nrc.ca:
    image: opencadc/alma-sia:1.0.0
    build: ./sia/
    networks:
      - 'alma'
    ports:
      - '15555:5555'
    depends_on:
      - 'obscore.cadc.dao.nrc.ca'
    volumes:
      - 'server_certs:/usr/local/share/ca-certificates'
    environment:
      CATALINA_OPTS: '-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca'
  obscore.cadc.dao.nrc.ca:
    image: opencadc/alma-tap:1.1.5
    build: ./obscore/
    ports:
      - '35555:5555'
    networks:
      - 'alma'
    env_file:
      - './obscore/docker/config/alma-tap.properties'
    volumes:
      - 'server_certs:/usr/local/share/ca-certificates'
  reg.cadc.dao.nrc.ca:
    image: opencadc/alma-reg:1.0.0
    build: ./reg/
    networks:
      - 'alma'
    ports:
      - '25555:5555'
    volumes:
      - './reg/docker/reg-resource-caps.properties:/root/config/reg-resource-caps.properties'
      - 'server_certs:/usr/local/share/ca-certificates'
    environment:
      CATALINA_OPTS: '-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca'

networks:
  alma:

volumes:
  server_certs:
    external: true