version: "3.7"
services:
  traefik:
    hostname: "${PROXY_HOST}"
    image: traefik:v2.5
    command:
        - "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.file.directory=/configuration/"
        - "--providers.file.watch=true"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
    networks:
      - "alma"
    volumes:
      - "server_certs:/server_certs:ro"
      - "proxy_config:/configuration:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  sia:
    image: opencadc/alma-sia:1.0.6
    networks:
      - "alma"
    command: "catalina.sh run"
    entrypoint: "/entrypoint/entrypoint.sh"
    ports:
      - "10001:5555"
    depends_on:
      - "tap"
      - "reg"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
      - "alma_sia_config:/root/config:ro"
      - "entrypoint_root:/entrypoint:ro"
    environment:
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=${PROXY_HOST}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sia.loadbalancer.server.port=8080"
      - "traefik.http.routers.sia.rule=PathPrefix(`/sia2`)"
      - "traefik.http.routers.sia.entrypoints=websecure"
      - "traefik.http.routers.sia.tls=true"
      - "traefik.http.routers.sia.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.sia.tls.domains[0].sans=*.cadc.dao.nrc.ca"
  tap:
    image: opencadc/alma-tap:1.1.19-2
    ports:
      - "10002:5555"
    networks:
      - "alma"
    command: "catalina.sh run"
    entrypoint: "/entrypoint/entrypoint.sh"
    environment:
      # Add -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555 for remote debug
      CATALINA_OPTS: "-Dalma.tapuser.username=${DATABASE_USER} -Dalma.tapuser.password=${DATABASE_PASSWORD} -Dalma.tapuser.driverClassName=oracle.jdbc.OracleDriver -Dalma.tapuser.url=jdbc:oracle:thin:@${DATABASE_HOST}:1521/${DATABASE_NAME} -Dca.nrc.cadc.reg.client.RegistryClient.host=${PROXY_HOST}"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
      - "entrypoint_root:/entrypoint:ro"
      - "alma_properties_config:/root/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tap.loadbalancer.server.port=8080"
      - "traefik.http.routers.tap.rule=PathPrefix(`/tap`)"
      - "traefik.http.routers.tap.entrypoints=websecure"
      - "traefik.http.routers.tap.tls=true"
      - "traefik.http.routers.tap.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.tap.tls.domains[0].sans=*.cadc.dao.nrc.ca"
      - "traefik.http.routers.tap.service=tap"
  reg:
    image: opencadc/alma-reg:1.0.3
    networks:
      - "alma"
    ports:
      - "10003:5555"
    volumes:
      - "alma_reg_config:/root/config"
      - "ca_certs:/usr/local/share/ca-certificates"
    environment:
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=${PROXY_HOST}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.reg.loadbalancer.server.port=8080"
      - "traefik.http.routers.reg.rule=PathPrefix(`/reg`)"
      - "traefik.http.routers.reg.entrypoints=websecure"
      - "traefik.http.routers.reg.tls=true"
      - "traefik.http.routers.reg.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.reg.tls.domains[0].sans=*.cadc.dao.nrc.ca"
      - "traefik.http.routers.reg.service=reg"
  data:
    image: opencadc/alma-data:1.1.4
    networks:
      - "alma"
    ports:
      - "10004:5555"
    volumes:
      - "alma_data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.data.loadbalancer.server.port=8080"
      - "traefik.http.routers.data.rule=PathPrefix(`/data`)"
      - "traefik.http.routers.data.entrypoints=websecure"
      - "traefik.http.routers.data.tls=true"
      - "traefik.http.routers.data.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.data.tls.domains[0].sans=*.cadc.dao.nrc.ca"
  rh:
    image: opencadc/alma-cadc-rh:0.1
    command: "mix phx.server"
    networks:
      - "alma"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.rh.loadbalancer.server.port=4000"
      - "traefik.http.routers.rh.rule=PathPrefix(`/rh`)"
      - "traefik.http.routers.rh.entrypoints=websecure"
      - "traefik.http.routers.rh.tls=true"
      - "traefik.http.routers.rh.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.rh.tls.domains[0].sans=*.cadc.dao.nrc.ca"
      - "traefik.http.routers.rh.service=rh"
  datalink:
    image: opencadc/alma-datalink:1.3.5
    networks:
      - "alma"
    command: "catalina.sh run"
    entrypoint: "/entrypoint/entrypoint.sh"
    environment:
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=${PROXY_HOST} -Djsse.enableSNIExtension=false"
    ports:
      - "10005:5555"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
      - "alma_properties_config:/root/config"
      - "entrypoint_root:/entrypoint:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.datalink.loadbalancer.server.port=8080"
      - "traefik.http.routers.datalink.rule=PathPrefix(`/datalink`)"
      - "traefik.http.routers.datalink.entrypoints=websecure"
      - "traefik.http.routers.datalink.tls=true"
      - "traefik.http.routers.datalink.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.datalink.tls.domains[0].sans=*.cadc.dao.nrc.ca"
  soda:
    image: opencadc/alma-soda:1.2.3
    ports:
      - "10006:5555"
    networks:
      - "alma"
    command: "catalina.sh run"
    entrypoint: "/entrypoint/entrypoint.sh"
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555 -Djava.security.egd=file:/dev/./urandom -Dca.nrc.cadc.reg.client.RegistryClient.host=${PROXY_HOST}"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
      - "alma_properties_config:/root/config"
      - "entrypoint_root:/entrypoint:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.soda.loadbalancer.server.port=8080"
      - "traefik.http.routers.soda.rule=PathPrefix(`/soda`)"
      - "traefik.http.routers.soda.entrypoints=websecure"
      - "traefik.http.routers.soda.tls=true"
      - "traefik.http.routers.soda.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.soda.tls.domains[0].sans=*.cadc.dao.nrc.ca"

networks:
  alma:

volumes:
  server_certs:
    external: true
  ca_certs:
    external: true
  proxy_config:
    external: true
  alma_data:
    external: true
  alma_properties_config:
    external: true
  alma_sia_config:
    external: true
  alma_reg_config:
    external: true
  alma_rh_config:
    external: true
  alma_rh_root:
    external: true
  entrypoint_root:
    external: true
