version: "3.2"
services:
  proxy.cadc.dao.nrc.ca:
    image: nginx:alpine
    ports:
      - '443:443'
    networks:
      - 'alma'
    volumes:
      - './docker/proxy/default-ssl.conf:/etc/nginx/conf.d/default.conf'
      - 'server_certs:/usr/share/nginx/certs'
    depends_on:
      - 'obscore.cadc.dao.nrc.ca'
      - 'sia.cadc.dao.nrc.ca'
      - 'reg.cadc.dao.nrc.ca'
  sia:
    image: opencadc/alma-sia:1.0.0
    build: ./sia/
    networks:
      - "alma"
    ports:
      - "15555:5555"
    depends_on: 
      - "obscore"
    environment: 
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=reg"
  obscore:
    image: opencadc/alma-tap:1.1.5
    build: ./obscore/
    depends_on:
      - "obscoredb"
    ports:
      - "35555:5555"
    networks:
      - "alma"
    env_file:
      - "./obscore/docker/config/alma-tap.properties"
    environment: 
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=reg"
  obscoredb:
    image: opencadc/tap-oracle:11-xe
    shm_size: 1gb
    networks:
      - "alma"
    volumes:
      - "./obscore/docker/sql:/docker-entrypoint-initdb.d/startup"
  reg:
    image: opencadc/alma-reg:1.0.0
    build: ./reg/
    networks:
      - "alma"
    ports:
      - "25555:5555"
    environment: 
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=reg"

networks:
  alma:

volumes:
  server_certs:
    external: true
