version: "3.2"
services:
  traefik:
    hostname: proxy.cadc.dao.nrc.ca
    image: traefik:v2.2
    command:
        - "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.file.directory=/configuration/"
        - "--providers.file.watch=true"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
    networks:
      - "alma"
    volumes:
      - "server_certs:/server_certs"
      - "./docker/proxy:/configuration:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  sia:
    image: opencadc/alma-sia:1.0.3
    networks:
      - "alma"
    ports:
      - "15555:5555"
    depends_on:
      - "obscore"
      - "reg"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
      - "./sia/docker/SiaRunner.properties:/root/config/SiaRunner.properties"
    environment:
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sia.loadbalancer.server.port=8080"
      - "traefik.http.routers.sia.rule=PathPrefix(`/sia2`)"
      - "traefik.http.routers.sia.entrypoints=websecure"
      - "traefik.http.routers.sia.tls=true"
      - "traefik.http.routers.sia.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.sia.tls.domains[0].sans=*.cadc.dao.nrc.ca"
  obscore:
    image: opencadc/alma-tap:1.1.14
    ports:
      - "35555:5555"
    networks:
      - "alma"
    env_file:
      - "./obscore/docker/config/alma-tap.properties"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.obscore.loadbalancer.server.port=8080"
      - "traefik.http.routers.obscore.rule=PathPrefix(`/tap`)"
      - "traefik.http.routers.obscore.entrypoints=websecure"
      - "traefik.http.routers.obscore.tls=true"
      - "traefik.http.routers.obscore.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.obscore.tls.domains[0].sans=*.cadc.dao.nrc.ca"
  reg:
    image: opencadc/alma-reg:1.0.1
    networks:
      - "alma"
    ports:
      - "25555:5555"
    volumes:
      - "./reg/docker/reg-resource-caps.properties:/root/config/reg-resource-caps.properties"
      - "ca_certs:/usr/local/share/ca-certificates"
    environment:
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.reg.loadbalancer.server.port=8080"
      - "traefik.http.routers.reg.rule=PathPrefix(`/reg`)"
      - "traefik.http.routers.reg.entrypoints=websecure"
      - "traefik.http.routers.reg.tls=true"
      - "traefik.http.routers.reg.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.reg.tls.domains[0].sans=*.cadc.dao.nrc.ca"
  datalink:
    image: opencadc/alma-datalink:1.2.0
    networks:
      - "alma"
    env_file:
      - "./datalink/docker/config/alma-datalink.properties"
    ports:
      - "45555:5555"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
      - "./org.opencadc.alma.properties:/root/config/org.opencadc.alma.properties"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.datalink.loadbalancer.server.port=8080"
      - "traefik.http.routers.datalink.rule=PathPrefix(`/datalink`)"
      - "traefik.http.routers.datalink.entrypoints=websecure"
      - "traefik.http.routers.datalink.tls=true"
      - "traefik.http.routers.datalink.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.datalink.tls.domains[0].sans=*.cadc.dao.nrc.ca"
  soda:
    image: opencadc/alma-soda:1.1.0
    ports:
      - "55555:5555"
    networks:
      - "alma"
    env_file:
      - "./soda/docker/config/alma-soda.properties"
    volumes:
      - "ca_certs:/usr/local/share/ca-certificates"
      - "./org.opencadc.alma.properties:/root/config/org.opencadc.alma.properties"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.soda.loadbalancer.server.port=8080"
      - "traefik.http.routers.soda.rule=PathPrefix(`/soda`)"
      - "traefik.http.routers.soda.entrypoints=websecure"
      - "traefik.http.routers.soda.tls=true"
      - "traefik.http.routers.soda.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.soda.tls.domains[0].sans=*.cadc.dao.nrc.ca"

networks:
  alma:

volumes:
  server_certs:
    external: true
  ca_certs:
    external: true
