version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    hostname: ${HOSTNAME:-proxy.cadc.dao.nrc.ca}
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'alma'
    volumes:
      - './docker/proxy/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - 'obscore.cadc.dao.nrc.ca'
      - 'sia.cadc.dao.nrc.ca'
      - 'reg.cadc.dao.nrc.ca'
      - 'soda.cadc.dao.nrc.ca'
      - 'datalink.cadc.dao.nrc.ca'
  sia.cadc.dao.nrc.ca:
    image: opencadc/alma-sia:1.0.2
    networks:
      - 'alma'
    ports:
      - '15555:5555'
    depends_on:
      - 'obscore.cadc.dao.nrc.ca'
    environment:
      CATALINA_OPTS: '-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca'
  obscore.cadc.dao.nrc.ca:
    image: opencadc/alma-tap:1.1.13
    ports:
      - '35555:5555'
    networks:
      - 'alma'
    env_file:
      - './obscore/docker/config/alma-tap.properties'
  datalink.cadc.dao.nrc.ca:
    image: opencadc/alma-datalink:1.0.0
    networks:
      - "alma"
    env_file:
      - "./datalink/docker/config/alma-datalink.properties"
    ports:
      - "45555:5555"
    volumes:
      - "./org.opencadc.alma.properties:/root/config/org.opencadc.alma.properties"
  reg.cadc.dao.nrc.ca:
    image: opencadc/alma-reg:1.0.1
    networks:
      - 'alma'
    ports:
      - '25555:5555'
    environment:
      CATALINA_OPTS: '-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca'
  soda.cadc.dao.nrc.ca:
    image: opencadc/alma-soda:1.0.0
    ports:
      - '55555:5555'
    networks:
      - 'alma'
    volumes:
      - "./org.opencadc.alma.properties:/root/config/org.opencadc.alma.properties"

networks:
  alma:
