version: "3.2"
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - "alma"
    volumes:
      - "./docker/proxy/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "obscore"
      - "sia"
      - "reg"
  sia:
    image: opencadc/alma-sia:1.0.0
    build: ./sia/
    networks:
      - "alma"
    ports:
      - "15555:5555"
    depends_on: 
      - "obscore"
    environment: 
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=reg"
  obscore:
    image: opencadc/alma-tap:1.1.6
    build: ./obscore/
    depends_on:
      - "obscoredb"
    ports:
      - "35555:5555"
    networks:
      - "alma"
    env_file:
      - "./obscore/docker/config/alma-tap.properties"
    environment: 
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=reg"
  obscoredb:
    image: opencadc/tap-oracle:11-xe
    shm_size: 1gb
    networks:
      - "alma"
    volumes:
      - "./obscore/docker/sql:/docker-entrypoint-initdb.d/startup"
  reg:
    image: opencadc/alma-reg:1.0.0
    build: ./reg/
    networks:
      - "alma"
    ports:
      - "25555:5555"
    environment: 
      CATALINA_OPTS: "-Dca.nrc.cadc.reg.client.RegistryClient.host=reg"

networks:
  alma:
