version: "3.2"
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - "reg"
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "reg"
  reg:
    image: opencadc/alma-reg:1.0.0
    networks:
      - "reg"
    ports:
      - "5555:5555"
#    volumes:
#      - "./reg.war:/usr/local/tomcat/webapps/reg.war"

networks:
  reg:
