version: "3.2"
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - "sia_obscore"
    volumes:
      - "./docker/proxy/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/proxy/html:/usr/share/nginx/html"
    depends_on:
      - "sia"
  sia:
    image: opencadc/alma-sia:1.0.3
    networks:
      - "sia_obscore"
    ports:
      - "8080:8080"
      - "5555:5555"
#    volumes:
#      - "./docker/SiaRunner.properties:/root/config/SiaRunner.properties"

networks:
  sia_obscore:
