version: "3.2"
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - "sia_obscore"
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
      - "./proxy/html:/usr/share/nginx/html"
    depends_on:
      - "sia"
  sia:
    image: opencadc/alma-sia:1.0.0
    networks:
      - "sia_obscore"
    ports:
      - "5555:5555"
    volumes:
      - "./sia.war:/usr/local/tomcat/webapps/sia.war"

networks:
  sia_obscore:
