version: "3.2"
services:
  proxy.cadc.dao.nrc.ca:
    image: nginx:alpine
    ports:
      - "443:443"
    networks:
      - "datalink"
    volumes:
      - "./docker/proxy/default-ssl.conf:/etc/nginx/conf.d/default.conf"
      - "server_certs:/usr/share/nginx/certs"
    depends_on:
      - "datalink.cadc.dao.nrc.ca"
  datalink.cadc.dao.nrc.ca:
    image: opencadc/alma-datalink:1.0.1
    ports:
      - "5555:5555"
    networks:
      - "datalink"
    volumes:
      - "./build/libs/datalink##1000.war:/usr/local/tomcat/webapps/datalink##1000.war"
    env_file:
      - "./docker/config/alma-datalink.properties"

networks:
  datalink:

volumes:
  server_certs:
    external: true
