name: Java+Docker CI

on: 
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: build, test, and install alma-lib
      run: cd alma-lib && gradle --info clean build test publishToMavenLocal
      
    - name: build and test data
      run: cd data && gradle --info clean build test
      
    - name: build and test datalink
      run: cd datalink && gradle --info clean build test

    - name: build and test tap
      run: cd tap && gradle --info clean build test

    - name: build and test reg
      run: cd reg && gradle --info clean build test

    - name: build and test sia
      run: cd sia && gradle --info clean build test

    - name: build and test soda
      run: cd soda && gradle --info clean build test