name: Java+Docker CI

on: 
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    # Temporary local build for cadc data ops fits library.
    - name: local build of cadc-data-ops-fits
      run: |
        cd ..
        git clone --single-branch --branch master https://github.com/opencadc/dal
        cd cadc-data-ops-fits
        gradle -i assemble install

    - name: build, test, and install alma-lib
      run: cd alma-lib && gradle --info clean build test install
      
    - name: build and test data
      run: cd data && gradle --info clean build test
      
    - name: build and test datalink
      run: cd datalink && gradle --info clean build test

    - name: build and test obscore
      run: cd obscore && gradle --info clean build test

    - name: build and test reg
      run: cd reg && gradle --info clean build test

    - name: build and test sia
      run: cd sia && gradle --info clean build test

    - name: build and test soda
      run: cd soda && gradle --info clean build test