name: Java+Docker CI

on: 
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: build, test, and install alma-lib
      run: cd alma-lib && gradle --info clean build test publishToMavenLocal

    # TODO: Upgrade to WCSLib 7?
    - name: install WCSLIB (libwcs5-15)
      run: |
        sudo apt-get update && sudo apt-get install -y curl gcc make \
        && curl -Lv -o /tmp/wcslib.tar.bz2 https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/wcslib/5.15-1/wcslib_5.15.orig.tar.bz2 \
        && cd /tmp/ \
        && tar jxvf wcslib.tar.bz2 \
        && cd wcslib-5.15 \
        && ./configure --prefix=/usr \
        && make && sudo make install

    - name: build Tomcat
      run: cd docker/tomcat && docker build -t opencadc/alma-tomcat:9-jdk11-openjdk-slim .

    - name: build and test data
      run: cd data && gradle --info clean build test
      
    - name: build and test datalink
      run: cd datalink && gradle --info clean build test

    - name: build and test tap
      run: cd tap && gradle --info clean build test

    - name: build and test reg
      run: cd reg && gradle --info clean build test

    - name: build and test sia
      run: cd sia && gradle --info clean build test

    - name: build and test soda
      run: cd soda && gradle --info clean build test
