name: Reusable Docker workflow

env:
  CI_REGISTRY_ORGANIZATION: opencadc

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  gradle-build:
    needs: install-alma-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/download-artifact@v2
        with:
          name: alma-lib
          path: /home/runner/.m2/repository/org/opencadc/alma-lib
      - name: build and test ${{ inputs.name }}
        run: gradle --info -b ${{ inputs.name }}/build.gradle clean build test
      # Upload WAR artifact
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.name }}-artifact
          path: ./${{ inputs.name }}/build/libs/${{ inputs.artifact-name }}.war